name: GitHub Page Update

on:
  workflow_run:
    workflows: ["Update Data"]
    types: [completed]
    branches:
      - 'main'
      - 'auto_data_update'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: gh-page

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Visualizations
        run: |
          mkdir docs
          python generate_html.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m '[bot] Automated github page update'
            git push origin ${{ env.BRANCH }}
          fi
