name: Update Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: auto_data_update

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --prefer-binary -r requirements.txt

    - name: Run data update script
      run: |
        python scripts/main.py

    - name: Check for changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m 'Automated data update'
        fi

    - name: Commit and push changes
      if: success()
      run: |
        git push origin auto_data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
